services:
  db:
    image: postgres:18.4
    container_name: tool_share_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  test_db:
      image: postgres:18.4
      container_name: tool_share_test_db
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: test_db
      ports:
        - "5434:5432"
  web:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: tool_share_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./server:/app 
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - TEST_DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@test_db:5432/test_db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - test_db
volumes:
  postgres_data: