"""Add pickup and return reminder sent flags in reservaitons table

Revision ID: 0fe42333dca6
Revises: 484890abe0ac
Create Date: 2026-07-25 07:00:05.042177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fe42333dca6"
down_revision: Union[str, Sequence[str], None] = "484890abe0ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservations",
        sa.Column(
            "pickup_reminder_sent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the pickup reminder has been sent",
        ),
    )
    op.add_column(
        "reservations",
        sa.Column(
            "return_reminder_sent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the return reminder has been sent",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservations", "return_reminder_sent")
    op.drop_column("reservations", "pickup_reminder_sent")
    # ### end Alembic commands ###
