"""Create messages table

Revision ID: 1420f6f97e79
Revises: 0fe42333dca6
Create Date: 2026-07-27 21:23:10.629308

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1420f6f97e79"
down_revision: Union[str, Sequence[str], None] = "0fe42333dca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for each message",
        ),
        sa.Column(
            "reservation_id",
            sa.UUID(),
            nullable=False,
            comment="Links the message to the reservation",
        ),
        sa.Column(
            "sender_id",
            sa.UUID(),
            nullable=False,
            comment="Links the message to the user who sent it",
        ),
        sa.Column(
            "content", sa.Text(), nullable=False, comment="Text content of the message"
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the message is read",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the message was sent",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_messages_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("fk_messages_sender_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        comment="Table for storing messages between users within a reservation",
    )
    op.create_index(
        "ix_messages_reservation_created",
        "messages",
        ["reservation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_reservation_created", table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
