"""Create reservations table

Revision ID: 1af5d799b4ba
Revises: e4bd78f9fbab
Create Date: 2026-07-13 20:52:31.170949

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1af5d799b4ba"
down_revision: Union[str, Sequence[str], None] = "e4bd78f9fbab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a reservation",
        ),
        sa.Column(
            "tool_id",
            sa.UUID(),
            nullable=False,
            comment="Links the reservation to the tool that involved in the borrowing/lending cycle",
        ),
        sa.Column(
            "borrower_id",
            sa.UUID(),
            nullable=False,
            comment="Links the reservation to the user requesting the tool",
        ),
        sa.Column(
            "pickup_notes",
            sa.Text(),
            nullable=True,
            comment="Instructions for picking up the tool",
        ),
        sa.Column(
            "return_notes",
            sa.Text(),
            nullable=True,
            comment="Instructions for returning the tool",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "APPROVED",
                "PICKED_UP",
                "RETURNED",
                "DENIED",
                "CANCELED",
                name="reservationstatus",
                native_enum=False,
            ),
            server_default=sa.text("'REQUESTED'"),
            nullable=False,
            comment="The current status of the reservation",
        ),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Planned calendar reservation start date",
        ),
        sa.Column(
            "end_date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Planned calendar reservation return date",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the reservation was created",
        ),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["users.id"],
            name=op.f("fk_reservations_borrower_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"], ["tools.id"], name=op.f("fk_reservations_tool_id_tools")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
        comment="Table for managing the borrowing/lending cycle of tools",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservations")
    # ### end Alembic commands ###
