"""Added default uuid for users table

Revision ID: 2f44c1f6b69b
Revises: 9a841aa64b82
Create Date: 2026-06-24 06:12:35.279182

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f44c1f6b69b"
down_revision: Union[str, Sequence[str], None] = "9a841aa64b82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_photo_id_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_photo_id"), "users", ["photo_id"])
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_photo_id"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_photo_id_key"),
        "users",
        ["photo_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
