"""Create notification table

Revision ID: 484890abe0ac
Revises: c2715567d723
Create Date: 2026-07-24 03:36:08.571513

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "484890abe0ac"
down_revision: Union[str, Sequence[str], None] = "c2715567d723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a notification",
        ),
        sa.Column(
            "recipient_id",
            sa.UUID(),
            nullable=False,
            comment="Links the notification to the user who received it",
        ),
        sa.Column(
            "category",
            sa.Enum(
                "RESERVATION",
                "MESSAGE",
                "REPORT",
                "REVIEW",
                "INVITATION",
                "SYSTEM",
                name="notificationcategory",
                native_enum=False,
            ),
            server_default=sa.text("'SYSTEM'"),
            nullable=False,
            comment="Category of the notification",
        ),
        sa.Column(
            "title",
            sa.String(length=150),
            nullable=False,
            comment="Title of the notification",
        ),
        sa.Column(
            "content", sa.Text(), nullable=False, comment="Content of the notification"
        ),
        sa.Column(
            "target_id",
            sa.UUID(),
            nullable=True,
            comment="Target id of the notification",
        ),
        sa.Column(
            "target_type",
            sa.String(length=50),
            nullable=True,
            comment="Target type of the notification",
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the notification is read",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the reservation was created",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        comment="Table for managing user notifications",
    )
    op.create_index(
        "idx_notifications_user_read_status",
        "notifications",
        ["recipient_id", "is_read", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_notifications_user_read_status", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
