"""Create reviews table

Revision ID: 49bf7492ea4d
Revises: 3097c6e3e5a1
Create Date: 2026-07-20 06:22:31.621507

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49bf7492ea4d"
down_revision: Union[str, Sequence[str], None] = "3097c6e3e5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a review",
        ),
        sa.Column(
            "reservation_id",
            sa.UUID(),
            nullable=False,
            comment="Links the review to the reservation",
        ),
        sa.Column(
            "reviewer_id",
            sa.UUID(),
            nullable=False,
            comment="Links the review to the user who submitted the review",
        ),
        sa.Column(
            "reviewee_id",
            sa.UUID(),
            nullable=False,
            comment="Links the review to the user who received the review",
        ),
        sa.Column(
            "rating", sa.Integer(), nullable=False, comment="Review rating from 1 to 5"
        ),
        sa.Column(
            "comment",
            sa.Text(),
            nullable=True,
            comment="Review comment provided by the reviewer",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the reservation was created",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reviews_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewee_id"],
            ["users.id"],
            name=op.f("fk_reviews_reviewee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_reviews_reviewer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "reservation_id", "reviewer_id", name="uq_reservation_reviewer"
        ),
        comment="Table that store rating and feedback about reservation after it is completed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    # ### end Alembic commands ###
