"""Create tools table

Revision ID: 49d9b2135e5c
Revises: 5ca04af118a7
Create Date: 2026-07-07 23:49:50.780201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49d9b2135e5c"
down_revision: Union[str, Sequence[str], None] = "5ca04af118a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_types",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the tool type",
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment='Uppercase code name of the tool category (e.g., "POWER_TOOLS")',
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable tool category for UI display",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Explanation of what belongs in this category",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_types")),
        sa.UniqueConstraint("code", name=op.f("uq_tool_types_code")),
        comment="Lookup table classifying equipment into searchable categories (e.g., Power Tools, Gardening).",
    )
    op.create_table(
        "tools",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a tool",
        ),
        sa.Column(
            "owner_id",
            sa.UUID(),
            nullable=False,
            comment="Links the tool to the user who owns and shares the tool",
        ),
        sa.Column(
            "tool_type_id",
            sa.Integer(),
            nullable=False,
            comment="Links the tool to the tool category",
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Name of the tool provided by the owner",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Details description of the tool provided by the owner",
        ),
        sa.Column(
            "condition",
            sa.Enum(
                "NEW", "GOOD", "FAIR", "POOR", name="toolcondition", native_enum=False
            ),
            nullable=False,
            comment="The condition of the tool provided by the owner",
        ),
        sa.Column(
            "pickup_notes",
            sa.Text(),
            nullable=True,
            comment="Instructions for picking up the tool",
        ),
        sa.Column(
            "return_notes",
            sa.Text(),
            nullable=True,
            comment="Instructions for returning the tool",
        ),
        sa.Column(
            "loan_duration_limit",
            sa.Integer(),
            server_default=sa.text("7"),
            nullable=True,
            comment="Maximum continuous days the user can request the tool",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "HIDDEN",
                "DELETED",
                "SUSPENDED",
                name="toolstatus",
                native_enum=False,
            ),
            server_default=sa.text("'AVAILABLE'"),
            nullable=False,
            comment="The current status of the tool",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the tool was added",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_tools_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["tool_type_id"],
            ["tool_types.id"],
            name=op.f("fk_tools_tool_type_id_tool_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tools")),
        comment="Table for storing all registered tools by owners for community sharing",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tools")
    op.drop_table("tool_types")
    # ### end Alembic commands ###
