"""Create invitations table

Revision ID: 76519d3d5daa
Revises: 71f4b9017e5a
Create Date: 2026-07-01 20:29:16.063676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76519d3d5daa"
down_revision: Union[str, Sequence[str], None] = "71f4b9017e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for an invitation",
        ),
        sa.Column(
            "invitation_token",
            sa.String(length=255),
            nullable=False,
            comment="The secure random string sent via email",
        ),
        sa.Column(
            "sender_id",
            sa.UUID(),
            nullable=False,
            comment="Links the invitation to the existing user who sent the invite link",
        ),
        sa.Column(
            "recipient_email",
            sa.String(length=255),
            nullable=False,
            comment="Target email address the invite was sent to",
        ),
        sa.Column(
            "recipient_id",
            sa.UUID(),
            nullable=True,
            comment="Links the invitation to a new user profile created via this invite",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "EXPIRED",
                "REVOKED",
                name="invitationstatus",
                native_enum=False,
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
            comment="The status of the invite token",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the invite link was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now()) + INTERVAL '7 days'"),
            nullable=False,
            comment="Date and time the invite link is expired",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_invitations_recipient_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("fk_invitations_sender_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint(
            "invitation_token", name=op.f("uq_invitations_invitation_token")
        ),
        comment="Table for tracking peer-to-peer neighborhood registration tokens used to control application access",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitations")
    # ### end Alembic commands ###
