"""Modified user table, added lookup tables. Created photos table

Revision ID: 9a841aa64b82
Revises: 4600412c18e7
Create Date: 2026-06-20 07:45:40.810149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a841aa64b82'
down_revision: Union[str, Sequence[str], None] = '4600412c18e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('users', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('users_photo_id_key', 'users', ['photo_id'])
    op.create_foreign_key('users_photo_id_fkey', 'users', 'photos', ['photo_id'], ['id'])
    op.create_foreign_key('users_status_id_fkey', 'users', 'user_statuses', ['status_id'], ['id'])
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'])
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.drop_constraint('users_photo_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_status_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_photo_id_key', 'users', type_='unique')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'status_id')
    op.drop_column('users', 'photo_id')
    op.drop_table('user_statuses')
    op.drop_table('user_roles')
    op.drop_table('photos')
    # ### end Alembic commands ###
