"""Create tool_photos table

Revision ID: a6e5dc55557d
Revises: 49d9b2135e5c
Create Date: 2026-07-09 01:52:36.293978

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6e5dc55557d"
down_revision: Union[str, Sequence[str], None] = "49d9b2135e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_photos",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a tool photo",
        ),
        sa.Column(
            "tool_id",
            sa.UUID(),
            nullable=False,
            comment="Links the tool photo to the tool",
        ),
        sa.Column(
            "photo_id",
            sa.UUID(),
            nullable=False,
            comment="Links the tool photo to the table where the photo is actually stored",
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photos.id"],
            name=op.f("fk_tool_photos_photo_id_photos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tools.id"],
            name=op.f("fk_tool_photos_tool_id_tools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_photos")),
        comment="Intersection table mapping multiple uploaded tool photo to individual tool",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_photos")
    # ### end Alembic commands ###
