"""add_database_comments

Revision ID: a8015845096e
Revises: 2f44c1f6b69b
Create Date: 2026-06-29 21:03:36.843515

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8015845096e"
down_revision: Union[str, Sequence[str], None] = "2f44c1f6b69b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "photos",
        "id",
        existing_type=sa.UUID(),
        comment="Unique identifier for a image",
        existing_nullable=False,
    )
    op.alter_column(
        "photos",
        "url",
        existing_type=sa.TEXT(),
        comment="The address hosting the actual image file",
        existing_nullable=False,
    )
    op.alter_column(
        "photos",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date and time the image was added",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "photos",
        "Table for storing unique URLs for uploaded images (profile photo, tool photos)",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "user_roles",
        "id",
        existing_type=sa.INTEGER(),
        comment="Unique identifier for the role",
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment='Uppercase code name of the role (e.g., "USER", "ADMIN")',
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        comment="Human-readable role name for UI display",
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "description",
        existing_type=sa.TEXT(),
        comment="Explanation of permissions assigned to the role",
        existing_nullable=True,
    )
    op.create_table_comment(
        "user_roles",
        "Lookup table defining user access levels",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "user_statuses",
        "id",
        existing_type=sa.INTEGER(),
        comment="Unique identifier for the account status",
        existing_nullable=False,
    )
    op.alter_column(
        "user_statuses",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment='Uppercase code name of the status (e.g., "ACTIVE", "SUSPENDED")',
        existing_nullable=False,
    )
    op.alter_column(
        "user_statuses",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        comment="Human-readable status name for UI display",
        existing_nullable=False,
    )
    op.alter_column(
        "user_statuses",
        "description",
        existing_type=sa.TEXT(),
        comment="Explanation of what limitations the user status has",
        existing_nullable=True,
    )
    op.create_table_comment(
        "user_statuses",
        "Lookup table defining user account status",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        comment="Unique identifier for each user",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Full name of the user",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="User's unique email address used for system login",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        comment="Securely hashed password string",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sa.TEXT(),
        comment="Brief personal bio or introduction written by the user",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "location",
        existing_type=sa.VARCHAR(length=255),
        comment="Location of the user",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "photo_id",
        existing_type=sa.UUID(),
        comment="Links the user to the user's uploaded profile picture",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "status_id",
        existing_type=sa.INTEGER(),
        comment="Links the user to their account status",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.INTEGER(),
        comment="Links the user to their system role",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date and time the user account was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "users",
        "Table for user profiles, authentication credentials, and account settings",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "users",
        existing_comment="Table for user profiles, authentication credentials, and account settings",
        schema=None,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date and time the user account was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Links the user to their system role",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "status_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Links the user to their account status",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "photo_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Links the user to the user's uploaded profile picture",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "location",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Location of the user",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Brief personal bio or introduction written by the user",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Securely hashed password string",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="User's unique email address used for system login",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Full name of the user",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique identifier for each user",
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.drop_table_comment(
        "user_statuses",
        existing_comment="Lookup table defining user account status",
        schema=None,
    )
    op.alter_column(
        "user_statuses",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Explanation of what limitations the user status has",
        existing_nullable=True,
    )
    op.alter_column(
        "user_statuses",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Human-readable status name for UI display",
        existing_nullable=False,
    )
    op.alter_column(
        "user_statuses",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment='Uppercase code name of the status (e.g., "ACTIVE", "SUSPENDED")',
        existing_nullable=False,
    )
    op.alter_column(
        "user_statuses",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Unique identifier for the account status",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "user_roles",
        existing_comment="Lookup table defining user access levels",
        schema=None,
    )
    op.alter_column(
        "user_roles",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Explanation of permissions assigned to the role",
        existing_nullable=True,
    )
    op.alter_column(
        "user_roles",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Human-readable role name for UI display",
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "code",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment='Uppercase code name of the role (e.g., "USER", "ADMIN")',
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Unique identifier for the role",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "photos",
        existing_comment="Table for storing unique URLs for uploaded images (profile photo, tool photos)",
        schema=None,
    )
    op.alter_column(
        "photos",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date and time the image was added",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "photos",
        "url",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The address hosting the actual image file",
        existing_nullable=False,
    )
    op.alter_column(
        "photos",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique identifier for a image",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
