"""Create password_resets table

Revision ID: e8c84b3977d7
Revises: 136b2a22fa9d
Create Date: 2026-08-01 08:41:31.293274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8c84b3977d7"
down_revision: Union[str, Sequence[str], None] = "136b2a22fa9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_resets",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for a password reset",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Links the password reset to the existing user",
        ),
        sa.Column(
            "reset_token",
            sa.String(length=255),
            nullable=False,
            comment="The secure random string sent via email",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "USED",
                "EXPIRED",
                name="passwordresetstatus",
                native_enum=False,
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
            comment="Status of the password reset request",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the password reset link was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now()) + INTERVAL '1 HOURS'"),
            nullable=False,
            comment="Date and time the password reset link is expired",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_resets_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_resets")),
        sa.UniqueConstraint("reset_token", name=op.f("uq_password_resets_reset_token")),
        comment="Table for tracking password reset requests",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_resets")
    # ### end Alembic commands ###
