"""Create reports table

Revision ID: ed5fdff72e0f
Revises: e8c84b3977d7
Create Date: 2026-08-02 07:32:13.156392

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed5fdff72e0f"
down_revision: Union[str, Sequence[str], None] = "e8c84b3977d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for each report",
        ),
        sa.Column(
            "reporter_id",
            sa.UUID(),
            nullable=False,
            comment="Links the report to the user who submitted the report",
        ),
        sa.Column(
            "category",
            sa.Enum(
                "LATE_RETURN",
                "TOOL_DAMAGED",
                "INAPPROPRIATE_BEHAVIOR",
                "OTHER",
                name="reportcategory",
                native_enum=False,
            ),
            server_default=sa.text("'OTHER'"),
            nullable=False,
            comment="Category of the report",
        ),
        sa.Column(
            "description", sa.Text(), nullable=False, comment="Content of the report"
        ),
        sa.Column(
            "target_id", sa.UUID(), nullable=False, comment="Target id of the report"
        ),
        sa.Column(
            "target_type",
            sa.Enum(
                "RESERVATION",
                "TOOL",
                "USER",
                name="reporttargettype",
                native_enum=False,
            ),
            nullable=False,
            comment="Target type of the report",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RESOLVED", name="reportstatus", native_enum=False),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
            comment="Status of the report",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the report was sent",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_reports_reporter_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        comment="Table that contain records about user reports about a reservation, tool, or another user",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    # ### end Alembic commands ###
