"""Initial migration. Add tables: users, user_roles, user_statuses, photos

Revision ID: f9635f5bf9df
Revises:
Create Date: 2026-07-01 06:32:38.431381

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9635f5bf9df"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for a image"
        ),
        sa.Column(
            "url",
            sa.Text(),
            nullable=False,
            comment="The address hosting the actual image file",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the image was added",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
        comment="Table for storing unique URLs for uploaded images (profile photo, tool photos)",
    )
    op.create_table(
        "user_roles",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the role",
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment='Uppercase code name of the role (e.g., "USER", "ADMIN")',
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable role name for UI display",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Explanation of permissions assigned to the role",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_user_roles_code")),
        comment="Lookup table defining user access levels",
    )
    op.create_table(
        "user_statuses",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for the account status",
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment='Uppercase code name of the status (e.g., "ACTIVE", "SUSPENDED")',
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable status name for UI display",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Explanation of what limitations the user status has",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_statuses")),
        sa.UniqueConstraint("code", name=op.f("uq_user_statuses_code")),
        comment="Lookup table defining user account status",
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for each user",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Full name of the user",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User's unique email address used for system login",
        ),
        sa.Column(
            "password",
            sa.String(length=255),
            nullable=False,
            comment="Securely hashed password string",
        ),
        sa.Column(
            "bio",
            sa.Text(),
            nullable=True,
            comment="Brief personal bio or introduction written by the user",
        ),
        sa.Column(
            "location",
            sa.String(length=255),
            nullable=True,
            comment="Location of the user",
        ),
        sa.Column(
            "photo_id",
            sa.UUID(),
            nullable=True,
            comment="Links the user to the user's uploaded profile picture",
        ),
        sa.Column(
            "status_id",
            sa.Integer(),
            nullable=False,
            comment="Links the user to their account status",
        ),
        sa.Column(
            "role_id",
            sa.Integer(),
            nullable=False,
            comment="Links the user to their system role",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
            comment="Date and time the user account was created",
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"], ["photos.id"], name=op.f("fk_users_photo_id_photos")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["user_roles.id"], name=op.f("fk_users_role_id_user_roles")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["user_statuses.id"],
            name=op.f("fk_users_status_id_user_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("photo_id", name=op.f("uq_users_photo_id")),
        comment="Table for user profiles, authentication credentials, and account settings",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("user_statuses")
    op.drop_table("user_roles")
    op.drop_table("photos")
    # ### end Alembic commands ###
