name: Python CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with: 
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./backend/qa/requirements-qa.txt
      
      # Pytest with Docker
      - name: Run pytest tests 
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: tool_share_test
          SECRET_KEY: some_testing_secret_key_12345678
        run: |
          docker compose run --rm web pytest
          docker compose down --volumes
        
      - name: Run Ruff linter 
        run: python -m ruff check . 

      - name: Run SQLFluff linter 
        run: python -m sqlfluff lint --dialect postgres .
        
#      - name: Run pip-audit linter
#        run: python -m pip_audit